name: Ghostsystem
version: '1.0'
main: de.ghost.ghostsystem.Ghostsystem
api-version: '1.20'
commands:
  meinschwert:
    permission: ghostsys.meinschwert
  adminitems:
    permission: ghostsys.adminitems
  heal:
    description: Heilt Spieler
  clearchat:
    description: Clear den Chat
  kopf:
    description: erhalte den Kopf des Spielers
  ping:
    description: Pinge andere Spieler
  fly:
    description: Lasse andere Spieler fliegen
  vanish:
    description: Mache dich unsichrbar
    aliases: [v]
  ec:
    description: Enderchest
  gm1:
    description: Creative
  gm0:
    description: Survival
  gm3:
    description: Spectator
  warp:
    description: Warps
    permission: ghostsys.warp.manage








