name: Ghostsystem
version: '1.0'
main: de.ghost.ghostsystem.Ghostsystem
api-version: '1.20'
commands:
  meinschwert:
    permission: ghostsys.meinschwert
  adminitems:
    permission: ghostsys.adminitems
  warp:
    permission: warp.manage
  tpa:
    description: TPA to a player
  tpaccept:
    description: Accept a TPA request
  tpdeny:
    description: Deny a TPA request
  tpyes:
    description: Alias for /tpaccept
  tpno:
    description: Alias for /tpdeny




